export { type CaseDifficulty, type CaseStatus, type InvestigationState, type HintLevel, type HintCategory, type AchievementType, type AchievementRarity, type ScoreCategory, type NotificationType, type NPCRole, type RelationshipStatus, type EmotionalState, type ObservationCategory, type ObservationVisibility, type ContradictionType, type InvestigationPhase, type AnalyticsEventType, type SortOrder, type FilterOperator, type ConditionType, type DependencyType, type EvidenceType, type EvidenceCategory, type RelationshipType, type NodeType, type TheoryConnectionType, type TimelineEventType, type TaskStatus, type ProgressState, type UnlockType } from "./enums";
export * from "./value-objects";
export { type ValidationResult, type ValidationError, type ValidationWarning, type ValidationSuggestion, createValidationResult, createValidationError, createValidationWarning } from "./models/validation-result";
export { type InteractableObject, type InteractableObjectState, type InteractableAnimationType } from "./models/interactable-object";
export { type Location, type LocationType, type LocationState } from "./models/location";
export { type ObservationGroup, type ObservationRequirement } from "./models/observation-group";
export { type DialogueReference, type Statement } from "./models/dialogue-reference";
export { type TimelineGroup, type TimelineGroupType } from "./models/timeline-group";
export { type Relationship, type RelationshipSourceType } from "./models/relationship";
export { type Objective, type ObjectiveType } from "./models/objective";
export { type Task } from "./models/task";
export { type Inventory, type InventorySlot, type InventoryItem, type InventoryItemType } from "./models/inventory";
export { type SaveData, type SaveSlotType, type CloudSyncStatus, type SaveMetaData } from "./models/save-data";
export { type Statistics, type CaseDifficultyStatistics } from "./models/statistics";
export { type MediaAsset, type MediaAssetType, type Attachment, type AttachmentParentType } from "./models/media-asset";
export { type SearchResult, type Filter, type FilterGroup } from "./models/search-result";
export { type AnalyticsEventData as DomainAnalyticsEventData, type AnalyticsSession } from "./models/analytics-event";
export { type UnlockCondition, type Requirement, type RequirementSet } from "./models/unlock-condition";
export { type Tag, type Category } from "./models/tag";
export { type DomainErrorCode } from "./errors/error-codes";
export { type DomainErrorDetails, DomainError, CaseNotFoundError, CaseLockedError, EvidenceNotFoundError, EvidenceAlreadyCollectedError, ObservationNotFoundError, ObservationAlreadyMadeError, RequirementNotMetError, TimelineConflictError, TimelineEventNotFoundError, InvalidTheoryConnectionError, InvalidProgressError, SaveNotFoundError, SaveConflictError, SaveCorruptedError, ValidationError as DomainValidationError, DuplicateEvidenceError, RepositoryError, SerializationError, EngineError } from "./errors/domain-error";
export * from "./results";
export * from "./validators";
export * from "./repositories";
export * from "./events";
export * from "./commands";
export * from "./serialization";
export * from "./engines";
export { type PaginationParams, type PaginationResult, paginate, getPageRange, calculateOffset, calculateTotalPages, getVisiblePageNumbers } from "./utils/pagination";
export { type FilterOperator as UtilityFilterOperator, type FilterCriteria, applyFilters, createFilter, combineFilters, hasActiveFilters } from "./utils/filtering";
export { type SearchOptions, search, rankSearchResults, highlightMatches } from "./utils/searching";
export { generateId, generateTimestampId, generateShortId, generateNumericId, generateUuid, isValidId, sanitizeId } from "./utils/id-generator";
export { parseDate, formatDate, formatDuration, formatRelativeTime, isBefore, isAfter, sortByDate, daysBetween, isToday } from "./utils/date-utils";
export { deepClone, structuredCloneSafe } from "./utils/deep-clone";
export { deepEqual, shallowEqual, areSetsEqual } from "./utils/equality";
export { type SortDirection, sortByKey, sortByDateField, sortByScore, sortByMultiple, sortByString } from "./utils/sorting";
export { calculateAverageConfidence, calculateWeightedConfidence, combineConfidenceBoosts, degradeConfidence, normalizeConfidence, confidenceToPercentage, isConfidenceHigh, isConfidenceLow, certaintyFromEvidenceCount } from "./utils/confidence-calculator";
export { calculateOverallProgress, calculateWeightedProgress, calculateCategoryScore, estimateRemainingTime, calculateProgressionRate, interpolateProgress } from "./utils/progress-calculator";
export { type EvaluationContext, evaluateRequirement, evaluateRequirementSet, evaluateRequirements, getMissingRequirements, getRequirementProgress } from "./utils/requirement-evaluator";
