export const DomainErrorCode = {
  CASE_NOT_FOUND: "CASE_NOT_FOUND",
  CASE_ALREADY_EXISTS: "CASE_ALREADY_EXISTS",
  CASE_LOCKED: "CASE_LOCKED",
  CASE_ALREADY_COMPLETED: "CASE_ALREADY_COMPLETED",

  EVIDENCE_NOT_FOUND: "EVIDENCE_NOT_FOUND",
  EVIDENCE_ALREADY_COLLECTED: "EVIDENCE_ALREADY_COLLECTED",
  EVIDENCE_NOT_COLLECTED: "EVIDENCE_NOT_COLLECTED",
  EVIDENCE_REQUIREMENT_NOT_MET: "EVIDENCE_REQUIREMENT_NOT_MET",

  OBSERVATION_NOT_FOUND: "OBSERVATION_NOT_FOUND",
  OBSERVATION_ALREADY_MADE: "OBSERVATION_ALREADY_MADE",
  OBSERVATION_REQUIREMENT_NOT_MET: "OBSERVATION_REQUIREMENT_NOT_MET",

  TIMELINE_NOT_FOUND: "TIMELINE_NOT_FOUND",
  TIMELINE_CONFLICT: "TIMELINE_CONFLICT",
  TIMELINE_EVENT_NOT_FOUND: "TIMELINE_EVENT_NOT_FOUND",
  TIMELINE_EVENT_OUT_OF_ORDER: "TIMELINE_EVENT_OUT_OF_ORDER",

  THEORY_NOT_FOUND: "THEORY_NOT_FOUND",
  INVALID_THEORY_CONNECTION: "INVALID_THEORY_CONNECTION",
  CIRCULAR_THEORY_REFERENCE: "CIRCULAR_THEORY_REFERENCE",
  THEORY_REQUIREMENT_NOT_MET: "THEORY_REQUIREMENT_NOT_MET",

  NPC_NOT_FOUND: "NPC_NOT_FOUND",
  NPC_NOT_AVAILABLE: "NPC_NOT_AVAILABLE",
  INTERROGATION_NOT_UNLOCKED: "INTERROGATION_NOT_UNLOCKED",

  INVALID_DIALOGUE: "INVALID_DIALOGUE",
  DIALOGUE_NOT_FOUND: "DIALOGUE_NOT_FOUND",

  INVALID_PROGRESS: "INVALID_PROGRESS",
  PROGRESS_NOT_FOUND: "PROGRESS_NOT_FOUND",
  REQUIREMENT_NOT_MET: "REQUIREMENT_NOT_MET",
  PREREQUISITE_NOT_MET: "PREREQUISITE_NOT_MET",

  SAVE_NOT_FOUND: "SAVE_NOT_FOUND",
  SAVE_CONFLICT: "SAVE_CONFLICT",
  SAVE_CORRUPTED: "SAVE_CORRUPTED",
  SAVE_QUOTA_EXCEEDED: "SAVE_QUOTA_EXCEEDED",

  INVALID_INPUT: "INVALID_INPUT",
  INVALID_STATE: "INVALID_STATE",
  INVALID_OPERATION: "INVALID_OPERATION",

  ACHIEVEMENT_NOT_FOUND: "ACHIEVEMENT_NOT_FOUND",
  ACHIEVEMENT_ALREADY_UNLOCKED: "ACHIEVEMENT_ALREADY_UNLOCKED",

  INVENTORY_FULL: "INVENTORY_FULL",
  ITEM_NOT_FOUND: "ITEM_NOT_FOUND",
  ITEM_ALREADY_IN_INVENTORY: "ITEM_ALREADY_IN_INVENTORY",

  DUPLICATE_ENTITY: "DUPLICATE_ENTITY",
  ENTITY_NOT_FOUND: "ENTITY_NOT_FOUND",
  DEPENDENCY_NOT_MET: "DEPENDENCY_NOT_MET",
  VALIDATION_FAILED: "VALIDATION_FAILED",

  REPOSITORY_ERROR: "REPOSITORY_ERROR",
  SERIALIZATION_ERROR: "SERIALIZATION_ERROR",
  STORAGE_ERROR: "STORAGE_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  ENGINE_ERROR: "ENGINE_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type DomainErrorCode = (typeof DomainErrorCode)[keyof typeof DomainErrorCode];
