export {
  createInvestigationContext,
  createEmptyDiscoveries,
  createEmptyProgress,
  touchContext,
  addActivity,
  addLogEntry,
  addNotification,
  markNotificationRead,
  clearNotifications,
  addDiscovery,
  isDiscovered,
  getDiscoveryCount,
  setRuntimeVariable,
  getRuntimeVariable,
  setTemporaryCache,
  getTemporaryCache,
  startTimer,
  pauseTimer,
  resumeTimer,
  getTimerElapsed,
  expireTimer,
  cloneContext,
  getContextSummary,
} from "./investigation-context";
